### ISSUE TITLE
KeyError: key "W_0" not found

### ISSUE THREAD

**Issue by keithreid-sfw** [XabierGA/DNN_Julia#1]
Hi

Thanks for the article, it is one of the better ones I found and I am hoping to cite it and learn from/cannabilise your code. My topic is game theory and I need to understand how neural nets work. I am new to Julia. I get an error on my ubuntu 18.04 LTS/jupyter/Julia1.2.0 environment in Julia. I took your code from GitHub. Perhaps I am entering nonsensical parameters. I think that I am making it iterate through zero and that kills a dictionary function given Julia counts from 1. Just a hunch. I have benefited from your article even without the code.

bw

Keith

When I do:

train_nn(3 , [0 , 0 , 0 , 0 , 1] , [1 , 0 , 0 , 0 , 0] , 0.5 , 500)

I get this error:

KeyError: key "W_0" not found

Stacktrace:
 [1] getindex at ./dict.jl:477 [inlined]
 [2] model_forward_step(::Array{Int64,1}, ::Dict{Any,Any}) at ./In[5]:161
 [3] train_nn(::Int64, ::Array{Int64,1}, ::Array{Int64,1}, ::Float64, ::Int64) at ./In[5]:181
 [4] top-level scope at In[6]:1

**Comment by XabierGA** [comment]
Hi Keith, thank you for the interest.

You must introduce the dimensions of layers as an array. Following your own example, if you want 3 layers:

Layers_dim = [1,15,1]

If your X and Y are 1 dimensional and you want the hidden layer to be 15 dimensional (for instance)

**Comment by keithreid-sfw** [comment]
Fantastic. Very prompt. I’m sure that’ll sort me out.
